name: Go-Matrix

on: [push]

env:
    GIT_BRANCH: $$(echo "${GITHUB_REF}" | sed 's/^refs\/heads\///')

jobs:

  set-env-var:
    runs-on: ubuntu-latest
    steps:
      - name: Set branch name
        run: echo "::set-env name=BRANCH_NAME::$(echo $GITHUB_REF_NAME)"

#   build:
#     runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         go-version: [ '1.19', '1.20', '1.21.x' ]
#     steps:
#       - uses: actions/checkout@v3

#       - name: Setup Go ${{ matrix.go-version }}
#         uses: actions/setup-go@v4
#         with:
#           go-version: ${{ matrix.go-version }}

#       - name: Go init
#         run: go mod init file-server

#       - name: Build
#         run: go build -v ./...

#       - name: Test
#         run: go test -v ./...

  test:
    needs: set-env-var
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Print branch name
        run: echo $BRANCH_NAME

