# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches:
      - main
      - develop

jobs:

  Build-go-1-21:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.x'

    - name: Go init
      run: go mod init file-server

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

  Build-go-1-20:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
    
        - name: Set up Go
          uses: actions/setup-go@v4
          with:
            go-version: '1.20.x'
    
        - name: Go init
          run: go mod init file-server
    
        - name: Build
          run: go build -v ./...
    
        - name: Test
          run: go test -v ./...
